### ISSUE TITLE
ContextNotActiveException when using a custom LoggingProvider

### ISSUE THREAD

**Issue by klutzer** [quarkiverse/quarkus-logging-json#119]
Hi everyone!

I came across with an error when initializing quarkus with a pre-configured provider with a CDI dependency. Do you guys know what is the problem?

My class:
```kotlin
@Singleton
class JsonLoggingProvider @Inject constructor(
    private val requestId: RequestId
): JsonProvider {

    override fun writeTo(generator: JsonGenerator?, event: ExtLogRecord?) {
        generator?.writeStringField("requestId", requestId.get());
    }
}
```

Error:
```
java.lang.RuntimeException: javax.enterprise.context.ContextNotActiveException
        at io.quarkiverse.loggingjson.JsonFormatter.format(JsonFormatter.java:37)
        at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:32)
        at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:43)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:97)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:73)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:750)
        at org.jboss.logmanager.Logger.log(Logger.java:708)
        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
        at org.jboss.logging.Logger.infof(Logger.java:1125)
        at io.quarkus.bootstrap.runner.Timing.printStartupTime(Timing.java:102)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:886)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.enterprise.context.ContextNotActiveException
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:40)
        at com.banqi.ccbissuer.common.application.logging.RequestId_ClientProxy.arc$delegate(RequestId_ClientProxy.zig:42)
        at com.banqi.ccbissuer.common.application.logging.RequestId_ClientProxy.get(RequestId_ClientProxy.zig:99)
        at com.banqi.ccbissuer.common.application.logging.JsonLoggingProvider.writeTo(JsonLoggingProvider.kt:15)
        at com.banqi.ccbissuer.common.application.logging.JsonLoggingProvider_Subclass.writeTo$$superforward1(JsonLoggingProvider_Subclass.zig:102)
        at com.banqi.ccbissuer.common.application.logging.JsonLoggingProvider_Subclass$$function$$1.apply(JsonLoggingProvider_Subclass$$function$$1.zig:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at com.banqi.ccbissuer.common.application.logging.JsonLoggingProvider_Subclass.writeTo(JsonLoggingProvider_Subclass.zig:172)
        at io.quarkiverse.loggingjson.JsonFormatter.format(JsonFormatter.java:26)
        ... 27 more

```

**Comment by SlyngDK** [comment]
I have never used kotlin, and can not help with this.
This sounds like general use of CDI in kotlin, and not something about this library.
There is an example in the readme, for java.
