### ISSUE TITLE
No Java DateTime Objects for serialization supported

### ISSUE THREAD

**Issue by markuspichler** [quarkiverse/quarkus-logging-json#169]
There is no chance to add jsr310 java date time modules to jackson object mapper or directly use the global quarkus object mapper inside the logging framework.

kind regards,
Markus

**Comment by SlyngDK** [comment]
It is calling `objectMapper.findAndRegisterModules()`, so have you tested adding dependency.

If not working please provide details/example of your issue. It is pretty hard to guess, what you are doing.

**Comment by s-seidel** [comment]
@SlyngDK here is a reproducer project: https://github.com/s-seidel/quarkus-logging-json-datetime

When you run `mvn clean install -Pnative` then this error occurs in native mode:
```
LogManager error of type FORMAT_FAILURE: Formatting error
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDate` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: com.example.DataObject["demo"])
	at io.quarkiverse.loggingjson.JsonFormatter.format(JsonFormatter.java:39)
	at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:32)
	at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:43)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.ExtHandler.publishToNest{"timestamp":"2023-05-22T12:12:34.257+02:00","sequence":7,"loggerClassName":"org.jboss.logging.LoggeedHandlers(ExtHandler.java:97)
	at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
	at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:66)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:327)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.r","loggerName":"io.quarkus","level":"INFO","message":"code-with-quarkus 1.0.0-SNAPSHOT native (powelogmanager.LoggerNode.publish(LoggerNode.java:334)
	at org.jboss.logmanager.Logger.logRaw(Logger.javred by Quarkus 3.0.3.Final) started in 0.007s. ","threadName":"main","threadId":1,"hostName":"its-dea:750)
	at org.slf4j.impl.Slf4jLogger.log(Slf4jLogger.java:588)
	at org.slf4j.impl.Slf4jLogger.log(S-nb-00175","processId":31473}
{"timestamp":"2023-05-22T12:12:34.257+02:00","sequence":8,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus","level":"INFO","message":"Profile prod aclf4jLogger.java:579)
	at org.slf4j.impl.Slf4jLogger.info(Slf4jLogger.java:297)
	at com.example.AppLitivated. ","threadName":"main","threadId":1,"hostName":"its-de-nb-00175","processId":31473}
{"timestfecycleBean.onStart(AppLifecycleBean.java:21)
	at com.example.AppLifecycleBean_Observer_onStart_21bdamp":"2023-05-22T12:12:34.257+02:00","sequence":9,"loggerClassName":"org.jboss.logging.Logger","logg0a897e6bbf1fe654e08937fa647bdc962f9c.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.jerName":"io.quarkus","level":"INFO","message":"Installed features: [cdi, logging-json]","threadName"ava:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRec:"main","threadId":1,"hostName":"its-de-nb-00175","processId":31473}
order.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDate` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: com.example.DataObject["demo"])
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1306)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:733)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3208)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:389)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:2408)
	at io.quarkiverse.loggingjson.jackson.JacksonJsonGenerator.writeObjectField(JacksonJsonGenerator.java:53)
	at io.quarkiverse.loggingjson.providers.KeyValueStructuredArgument.writeTo(KeyValueStructuredArgument.java:22)
	at io.quarkiverse.loggingjson.providers.ArgumentsJsonProvider.writeTo(ArgumentsJsonProvider.java:57)
	at io.quarkiverse.loggingjson.JsonFormatter.format(JsonFormatter.java:28)
	... 30 more
```

**Comment by iqnev** [comment]
Hi @SlyngDK  do you know how to fix the above issue?

**Comment by SlyngDK** [comment]
@iqnev No, but if you find a solution, you are welcome to provide a PR, with docs or bugfix.
